import tomllib

with open("lib/sycamore/pyproject.toml", "rb") as f:
    pyproject = tomllib.load(f)

extras = [e for e in pyproject["tool"]["poetry"]["extras"].keys()]
extras.sort()
print()
print("### BEGIN Auto-generated by autogen-groups.py")
for e in extras:
    print(f"[tool.poetry.group.{e}.dependencies]")
    print(f'sycamore-ai = {{ path = "lib/sycamore", develop = true, extras = ["{e}"] }}')
    print()
print("# END Auto-generated by autogen-groups.py")
