#!/bin/bash
if [[ "$0" != "./apps/docker-base/gen-pyproject-copy.sh" ]]; then
   echo "Run me as ./apps/docker-base/gen-pyproject-copy.sh"
   exit 1
fi
echo "# Begin generated by $0"
# lib/sycamore is copied in its entirety, so don't include here
for i in $(find . -name pyproject.toml | fgrep -v .venv | fgrep -v lib/sycamore/pyproject.toml | fgrep -v './pyproject.toml' | sort); do
    dir="$(dirname "$i")"
    readme="${dir}/README.md"
    echo "COPY --link --chown=1000:1000 $i $readme ${dir}/"
done
echo "COPY --link --chown=app:app ./pyproject.toml ./poetry.lock ./README.md ./"
echo "# End generated by $0"
