[tool.poetry]
name = "sycamore-noop-root"
version = "0.0.1"
description = "Noop root project Jupyter container with sycamore preinstalled"
authors = ["aryn.ai <opensource@aryn.ai>"]
readme = "README.md"
repository = "https://github.com/aryn-ai/sycamore.git"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
