name: Doc Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  doclint:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grep Lint
        uses: ./.github/actions/greplint
